5 print"{clear}"
10 print"{home}"
15 print"     M        "
20 print"      M       "
25 print"      {cm p}M{cm p*5} "
30 print"  {cm p*6}M{cm i}C{cm e}I"
35 print"C{cm r}VVVVVV{cm l}*{cm k}{cm l}B"
40 print"CDC{cm y*5}{cm r}{cm u}M{cm r}K"
45 print"      {cm y*5}M{cm y} "
50 print"            M "
55 print"             M"
60 for d=1 to 50:next
65 print"{home}"
70 print"             N"
75 print"            N "
80 print"      {cm p*5}N{cm p} "
85 print"  {cm p*6}{cm e}{cm i}N{cm e}I"
90 print"C{cm r}VVVVVV{cm l}*{cm k}{cm l}B"
95 print" D {cm y*5}N{cm u}C{cm r}K"
100 print"      {cm y}N{cm y*5} "
105 print"      N       "
110 print"     N        "
115 for d=1 to 50:next
120 goto 10
